name: Report an issue on a pattern
description: Report any issues regarding a pattern on GOV.UK
title: "[Enter the name of the pattern]: [Enter the issue with pattern]"
labels: ["pattern"]
projects: ["alphagov/100"]
body:
  - type: markdown
    attributes:
      value: |
        # Steps to creating an issue for a GOV.UK pattern
        - Update the title according to the proposed format
        - In the textarea below, provide a detailed description of the issue
  - type: textarea
    attributes:
      label: "Description"
      description: "Describe the issue with the pattern"
    validations:
      required: true